language: cpp
cache: apt
env:
  - LLVM_VERSION=4.0.0
  - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
  - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
  - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
  - CXXFLAGS=-lc++
  - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang-$LLVM_VERSION
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
sudo: required
before_script:
  - sudo apt-get update
install:
  - sudo apt-get -qq install bison=3.0.4 flex=2.5.37 wget cmake
script:
  - make clean
  - make
  - sudo ./bin/test_suite